### ISSUE TITLE
LSP contracts cannot be mixed with openzeppelin upgradable

### ISSUE THREAD

**Issue by lykhonis** [lukso-network/lsp-smart-contracts#233]
OpenZeppelin upgradable contracts use Initializable contract from separate package. When deployed as a proxy, it force checks no constructors are defined, and no fields are initialized.

If one would like to create upgradable LSP 7/8, it would fail due the follow inheritance chain:

LSP contracts use:
```
@erc725/smart-contracts/contracts/custom/Initializable.sol
```

While it seems to be a copy of OpenZeppelin Initializable, it uses:
```
import {Address} from "@openzeppelin/contracts/utils/Address.sol";
```

When attempted to deploy it as a proxy, I receive:
```
@openzeppelin/contracts/utils/Address.sol:191: Use of delegatecall is not allowed
https://zpl.in/upgrades/error-002
```

Unfortunately, for now, I was not able to find a way to mix LSP7/8 contracts with upgradable contracts from OpenZeppelin.

**Comment by YamenMerhi** [comment]
Hey @lykhonis 
Thanks for reporting this issue, I know where this error is coming from and had some additional conflicts when using our Init Contracts with OZ Upgradeable contracts this week.

Basically, OZ Upgradeable, will not allow any contract containing `selfdestruct` or `delegatecall` to be deployed as a proxy. In your case, you want to deploy LSP7/LSP8 token contract as upgradeable and they are using the *Custom Initializable* from erc725 that contains the normal **Address** Library that contains `delegatecall` operation.

If we replace the code of Custom Initializable with the code from OZ upgradeable, the `https://zpl.in/upgrades/error-002` error will be gone. But still, since we're using a Custom Initilizable it will conflict with other contracts from OZ upgradeable since they use another initializable contract. 

We use a custom Initilizable contract to expose some variables for additional security checks in the future, but since now its making some conflicts we may need to remove it for now and find a solution for later. 

Also since we have the Core contract, we have some inherited modules from normal OZ contracts that will conflict with OZ upgradeable.

My solution for this in the short run and in order to make it work for the hackathon will be:
- Remove Custom Initializable contract and replace it with Initializable contract from OZ upgradeable.
- Remove the inheritance of contracts that will conflict with OZ upgradeable (Context, etc..)

In the long run:
- Think about the efficiency of the Core contract and the conflicts that will make when using the contracts with OZ upgradeable. Splitting the code between two repos for normal and upgradeable could be a solution where each repo uses different packages (example: Context for normal lsps, ContextUpgradeable for Init lsps, etc,,). 
I'm in favor of this solution, no conflicts > avoiding duplicated code with Core contracts.

Let's discuss 🚀 @lykhonis @CJ42 @skimaharvey
